# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9140804c06401274fa915129620171b21ec416694990f0bac35cc890ef393c6cf761544dfeb0488ec311af81df2be0b5a30e7aae9b56f9a3f5a626fe4128b7b

test:
  secret_key_base: f152fbf4e08f91ea3c47a46e8f385baed355a1fd64478e342f32bac035ad5e497363ca97ea51ec00d2f8e7a0a94264a9f642857d2543b198a6b9ec18657719db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
